---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssl-cert-expiry-teams-webhook
  namespace: prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-name
  target:
    name: certexpiry-teams-webhook
    creationPolicy: Owner
  data:
    - secretKey: webhook
      remoteRef:
        key: ssl-cert-expiry-teams-webhook
